algoritmo "maior_comloop"
// Função : Receber numeros até 0(zero) e encontrar o maior numero
// Autor : Tiago Valério
// Data : 26/04/2017
// Seção de Declarações 
var
numero, maior : Inteiro
numerosInformados : Caracter

inicio
// Seção de Comandos 
Escreval("Este algoritmo vai demonstar o maior valor informado!!!")
Escreval("A condição de parada é valor 0 (zero)!")
Escreva("Informe um número: ")
Leia(numero)
maior <- numero

numerosInformados <- ("TESTE" + Caracter(11))


fimalgoritmo
