algoritmo "exemplo_para"
// Função : Utilização do Para
// Autor : Tiago Valério
// Data : 03/05/2017
// Seção de Declarações 
var
numero, valorUsuario, tabuada : inteiro
inicio
// Seção de Comandos 
Escreva("Informe um número qualquer: ")
Leia(valorUsuario)
para numero de 1 ate 10 faca
     tabuada <- valorUsuario * numero
     Escreval("Tabuada ", valorUsuario, " X ", numero, " = ", tabuada)
     Escreval("---------------------------")
fimpara
fimalgoritmo
