algoritmo "verifica_intervalo"
// Função : Recebe um numero qualquer e verifica se esta dentro do intervalo entre 100 e 200
// Autor : Tiago Valério
// Data : 19/04/2017
// Seção de Declarações 
var
numero : Inteiro
inicio
// Seção de Comandos 

Escreva("Informe um número qualquer: ")
Leia(numero)

se ((numero >= 100) e (numero <= 200)) entao
   Escreva("O número: ", numero, " está no intervalo entre 100 e 200")
fimse;

fimalgoritmo
