algoritmo "verifica_maior_que_10"
// Função : Recebe um numero qualquer e verifica se eh maior que 10(dez)
// Autor : Tiago Valério
// Data : 19/04/2017
// Seção de Declarações 
var
numero : Inteiro
inicio

// Seção de Comandos 
Escreval("Este programa recebe um número e mostra uma mensagem quando for maior que 10(dez)")
Escreva("Informe um número qualquer: ")
Leia(numero)

se (numero > 10) entao
   Escreva("O número: ", numero, " é maior que 10(dez)!!!")
fimse

fimalgoritmo

