algoritmo "conversor de horas"
// Função : Receber uma quantidade de horas e demonstrar e equivalente em minutos
// Autor : Tiago Valério
// Data : 17/04/2017
// Seção de Declarações 
var

qtdeHoras, qtdeMinutos : Inteiro

inicio

// Seção de Comandos 
Escreva("Informe a quantidade de hora(s): ")
Leia(qtdeHoras)

qtdeMinutos <- qtdeHoras * 60

Escreva(qtdeHoras, " hora(s) equivalem a ", qtdeMinutos, " minutos.")

fimalgoritmo
