algoritmo "calcula area triangulo"
// Função : recebe as informações de base e altura e então aplica a formula da area
// Autor : Tiago Valerio
// Data : 17/04/2017
// Seção de Declarações 
var

base, altura, area : Numerico

inicio

// Seção de Comandos 
Escreva("Informe a base do triângulo: ")
Leia(base)

Escreva("Informe a altura do triângulo: ")
Leia(altura)

area <- (base * altura) / 2

Escreva("o triangulo de base: ", base, " e altura: ", altura, " tem area de: ", area)




fimalgoritmo
